package com.govcareer.auth.entity;

public enum AuditEventType {
    LOGIN_SUCCESS,
    LOGIN_FAILURE,
    PASSWORD_CHANGED,
    PROFILE_UPDATED,
    LOGOUT,
    TOKEN_REFRESH,
    REGISTRATION_SUCCESS,
    REGISTRATION_FAILURE,
    EMAIL_VERIFICATION_REQUESTED,
    EMAIL_VERIFIED,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_RESET_COMPLETED,
    ACCOUNT_LOCKED
}
